FROM mhart/alpine-node:10 as build

WORKDIR /app

COPY . .
RUN yarn

ARG back_url=https://api.holistic-erp.tu
ENV BACK_URL=$back_url

WORKDIR /app/front
RUN yarn prestart:front:prod

FROM nginx

COPY default.conf /etc/nginx/conf.d/
COPY --from=build /app/front/public /usr/share/nginx/html
