FROM mhart/alpine-node:10 as build

WORKDIR /app

COPY . .
RUN yarn

WORKDIR /app/front
RUN yarn prestart:front:prod

FROM nginx

COPY default.conf /etc/nginx/conf.d/
COPY --from=build /app/dist /usr/share/nginx/html
